### ISSUE TITLE
unable to start container

### ISSUE THREAD

**Issue by OkenKhuman** [vitobotta/docker-tunnel#1]
I have some problem with compose setup
```
  tunnel:
    image: nginx-tunnel
    environment:
      - PORTS="90:3000,443:3001"
    command:
      - proxy
    network_mode: "host"
    restart: unless-stopped
```
I got errors as 
```
...
tunnel_1  | server {
tunnel_1  |     listen 443;
tunnel_1  |
tunnel_1  |     proxy_pass 127.0.0.1:3001" of the "listen" directive in /etc/nginx/nginx.conf:42
tunnel_1  | nginx: [emerg] invalid port in "90;
tunnel_1  |
tunnel_1  |     proxy_pass 127.0.0.1:3000;
tunnel_1  |     proxy_responses 0;
tunnel_1  | }
...
```
I build the image without any change from your dockerfile
please help me out

**Comment by OkenKhuman** [comment]
Ok it started running but I have some problem with compose setup
```
  tunnel:
    image: nginx-tunnel
    environment:
      - PORTS="90:3000,443:3001"
    command:
      - proxy
    network_mode: "host"
    restart: unless-stopped
```
I got errors as 
```
...
tunnel_1  | server {
tunnel_1  |     listen 443;
tunnel_1  |
tunnel_1  |     proxy_pass 127.0.0.1:3001" of the "listen" directive in /etc/nginx/nginx.conf:42
tunnel_1  | nginx: [emerg] invalid port in "90;
tunnel_1  |
tunnel_1  |     proxy_pass 127.0.0.1:3000;
tunnel_1  |     proxy_responses 0;
tunnel_1  | }
...
```
